"""Added device_id to models

Revision ID: 36c81ec918fb
Revises: cb79e439910b
Create Date: 2025-04-15 17:26:49.341564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c81ec918fb'
down_revision = 'cb79e439910b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('sensor_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_data_id'], ['sensor_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_column('device_id')

    op.drop_table('image_data')
    # ### end Alembic commands ###
