"""Add image binary storage

Revision ID: 67b21afa4299
Revises: b4cb9986ad71
Create Date: 2025-04-23 18:57:49.576840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b21afa4299'
down_revision = 'b4cb9986ad71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_binary', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.drop_column('image_binary')

    # ### end Alembic commands ###
