"""Added is_fire_hazard field to ImageData

Revision ID: b4cb9986ad71
Revises: 36c81ec918fb
Create Date: 2025-04-23 17:53:08.309469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cb9986ad71'
down_revision = '36c81ec918fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fire_hazard', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.drop_column('is_fire_hazard')

    # ### end Alembic commands ###
